name: Zenity AppImage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 16 1/15 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: build
      run: |
        sudo apt update
        sudo apt install libfuse2 ninja-build
        sudo apt install libgtk-3-dev itstool gettext python3-pip
        sudo pip3 install meson
        wget https://raw.githubusercontent.com/Samueru-sama/Zenity-GTK3-AppImage/main/zenity-gtk3-appimage.sh
        chmod a+x ./zenity-gtk3-appimage.sh
        ./zenity-gtk3-appimage.sh
        mkdir dist
        mv *AppImage dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Zenity-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4
          with:
            name: Zenity-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
